version: 2

issues:
  exclude-rules:
    - path: apis/cloud.redhat.com/v1alpha1/groupversion_info.go
      linters:
        - gofmt
        - goimports
    - text: "dot-imports"
      linters:
        - revive
