apiVersion: v1
kind: Service
metadata:
  labels:
    operator-name: ephemeral-namespace-operator
  name: controller-manager-metrics-service-non-auth
  namespace: system
spec:
  ports:
  - name: metrics
    port: 9000
    targetPort: metrics
  selector:
    operator-name: ephemeral-namespace-operator
