apiVersion: v1
kind: Service
metadata:
  labels:
    operator-name: ephemeral-namespace-operator
  name: controller-metrics-non-auth
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    operator-name: ephemeral-namespace-operator
