---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bridge-user
rules:
- apiGroups:
  - extensions
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - update
  - patch
