# permissions for end users to view namespacepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacepool-viewer-role
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacepools/status
  verbs:
  - get
