# permissions for end users to edit namespacepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacepool-editor-role
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacepools/status
  verbs:
  - get
