# permissions for end users to edit namespacereservations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacereservation-editor-role
rules:
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacereservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacereservations/status
  verbs:
  - get
