
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - limitranges
  - namespaces
  - resourcequotas
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.redhat.com
  resources:
  - clowdenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.redhat.com
  resources:
  - frontendenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacereservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacereservations/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.redhat.com
  resources:
  - namespacereservations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloud.redhat.com
  resources:
  - pools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.redhat.com
  resources:
  - pools/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.redhat.com
  resources:
  - pools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.openshift.io
  resources:
  - projectrequests
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
