kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: example-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: 'Namespace where the application is running'
      name: NAMESPACE
      default: "default"
      type: string
    - description: 'Expected output'
      name: EXPECTED_OUTPUT
      default: "0"
      type: string
  workspaces:
  - name: cluster-credentials
    optional: true
  tasks:
    - name: run-unit-tests
      description: run unit tests
      params:
      - name: SNAPSHOT
        value: $(params.SNAPSHOT)
      - name: NAMESPACE
        value: $(params.NAMESPACE)
      - name: EXPECTED_OUTPUT
        value: $(params.EXPECTED_OUTPUT)
      taskSpec:
        params:
        - name: SNAPSHOT
        - name: NAMESPACE
        - name: EXPECTED_OUTPUT
        results:
        - name: TEST_OUTPUT
          description: Test output
        steps:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          env:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
          - name: NAMESPACE
            value: $(params.NAMESPACE)
          - name: EXPECTED_OUTPUT
            value: $(params.EXPECTED_OUTPUT)
          script: |
            . ./ci/helpers.sh
            TEST_OUTPUT=$(. ./ci/unit_tests.sh)