{
 "title": "Ephemeral Namespace Operator Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "pools", "label": "Pool Type", "query": { "query": "label_values(pool)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful Reservations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(reservations_by_requester_total{pool=~\"$pools\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Active Reservations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_reservation_total", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Failed Reservations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(failed_pool_reservations_total{pool=\"$pools\"})",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "ENO Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(eno_version) by (version)", "legendFormat": "{{version}}" }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Reservations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(active_reservation_total{controller=\"namespacereservation\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Reservation Duration Total (In Hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Total" } },
   "targets": [
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"1\"})",
     "legendFormat": "1"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"2\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"1\"})",
     "legendFormat": "2"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"4\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"2\"})",
     "legendFormat": "4"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"8\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"4\"})",
     "legendFormat": "8"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"24\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"8\"})",
     "legendFormat": "24"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"48\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"24\"})",
     "legendFormat": "48"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"168\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"48\"})",
     "legendFormat": "168"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"336\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"168\"})",
     "legendFormat": "336"
    },
    {
     "expr": "sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"inf+\"}) - sum(namespace_reservation_duration_average_bucket{controller=\"namespacereservation\",le=\"336\"})",
     "legendFormat": "inf+"
    }
   ]
  },
  {
   "title": "Reservations per Hour (default pool)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(namespace_reservation_duration_average_count{pool=\"default\", controller=\"namespacereservation\"}[1h])",
     "legendFormat": "Reservations per hour"
    }
   ]
  },
  {
   "title": "Reservations per Hour by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pool) (increase(reservations_by_requester_total[1h]))",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Total Reservations by Requester",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sort_desc(sum by(requester) (reservations_by_requester_total))",
     "legendFormat": "{{requester}}"
    }
   ]
  },
  {
   "title": "Top Requesters (All Time)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(requester) (reservations_by_requester_total))",
     "legendFormat": "{{requester}}"
    }
   ]
  },
  {
   "title": "Reservations by Pool",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pool) (reservations_by_requester_total)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Reconciliations Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{controller=~\"clowdenvironment|namespacepool|namespacereservation\"}[1m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Operation Rates per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(rest_client_requests_total[1m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "ENO Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=\"ephemeral-namespace-operator-system\", container=\"manager\"})",
     "legendFormat": "K8s Usage"
    },
    {
     "expr": "avg(go_memstats_alloc_bytes{container=\"manager\", namespace=\"ephemeral-namespace-operator-system\"})",
     "legendFormat": "Alloc Bytes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"manager\", namespace=\"ephemeral-namespace-operator-system\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"manager\", namespace=\"ephemeral-namespace-operator-system\"})"
    }
   ]
  },
  {
   "title": "WorkQueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(workqueue_depth{service=\"ephemeral-namespace-operator-controller-metrics-non-auth\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}