name: Base image auto update
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Set up skopeo
        run: sudo apt-get install -y skopeo    
      - name: Check ubi8-minimal change
        run: |
          echo "::set-output name=UBIVERSION::$(skopeo inspect docker://registry.access.redhat.com/ubi8/ubi-minimal:latest |jq '.Labels.url' |sed 's/"//g' |awk -F/ '{print $NF}')"
      - name: Check go-toolset change
        run: |
          echo "::set-output name=GOTOOLSETVER::$(skopeo inspect docker://registry.access.redhat.com/ubi8/go-toolset:latest |jq '.Labels.url' |sed 's/"//g' |awk -F/ '{print $NF}')""
  makeachange: 
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Do change if the version changed
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'webdev-spam-list <webdev-spam-list@redhat.com>'
          git checkout -b update
          sed -i "s/registry.access.redhat.com\/ubi8\/ubi-minimal:[0-9.-]*/registry.access.redhat.com\/ubi8\/ubi-minimal:${{ needs.checkout.outputs.UBIVERSION }}/" Dockerfile
          sed -i "s/registry.access.redhat.com\/ubi8\/go-toolset:[0-9.-]*/registry.access.redhat.com\/ubi8\/go-toolset:${{ needs.checkout.outputs.GOTOOLSETVER }}/" Dockerfile
          git add -A
          git commit -m "Update to ubi-minimal or go-toolset image" || echo "No changes to commit"
          git push -u origin update || git push -f origin update
      - name: Create pull request
        run: gh pr create --title 'Regular docker image update' --body 'Automation \o/' --reviewer maknop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
