---
name: Run Unit Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.adoc'
      - '.github/**'

jobs:

  testing:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        name: Set up golang 1.18
        with:
          go-version: 1.18
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install package and dependencies
        run: |
          make
      - name: Run Tests
        run: make test
